spring:
  application:
    name: checkin-api
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  cache:
    type: caffeine
    caffeine:
      spec: initialCapacity=50,maximumSize=200,expireAfterWrite=5m
  retry:
    max-attempts: 3
    backoff:
      delay: 1000
      multiplier: 2

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method

logging:
  level:
    com.andesairlines: INFO
    org.springframework.cache: DEBUG
    org.springframework.retry: DEBUG
    org.hibernate.SQL: DEBUG

server:
  port: 8080
  servlet:
    context-path: /api