spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 3
      minimum-idle: 1
      idle-timeout: 4000
      max-lifetime: 4000
      connection-test-query: SELECT 1
      validation-timeout: 1000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  cache:
    caffeine:
      spec: initialCapacity=50,maximumSize=200,expireAfterWrite=2m
logging:
  level:
    com.andesairlines: DEBUG
    org.springframework.cache: DEBUG
    org.springframework.retry: DEBUG
    org.hibernate.SQL: DEBUG