spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/checkin?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&socketTimeout=30000&connectTimeout=10000&tcpKeepAlive=true}
    username: ${DB_USERNAME:}
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 10000
      idle-timeout: 4000
      max-lifetime: 20000
      minimum-idle: 2
      maximum-pool-size: 10
      connection-test-query: SELECT 1
      validation-timeout: 2000
      keepalive-time: 2000
      leak-detection-threshold: 4000
      pool-name: HikariCP
      initialization-fail-timeout: 0
      connection-init-sql: SELECT 1
      auto-commit: true
      data-source-properties:
        useSSL: false
        allowPublicKeyRetrieval: true
        tcpKeepAlive: true
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        useCursorFetch: true
        maintainTimeStats: false
        useLocalTransactionState: true
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          time_zone: UTC
          batch_size: 20
        connection:
          provider_disables_autocommit: true
    open-in-view: false
  cache:
    caffeine:
      spec: initialCapacity=100,maximumSize=1000,expireAfterWrite=10m

server:
  port: ${PORT:8080}

logging:
  level:
    com.andesairlines: INFO
    org.springframework.cache: INFO
    org.springframework.retry: INFO
    org.springframework.web: INFO
    root: INFO