spring:
  datasource:
    url: ${DB_URL}?useSSL=true&requireSSL=true&verifyServerCertificate=true&autoReconnect=true&failOverReadOnly=false&maxReconnects=10&connectionTimeout=3000&socketTimeout=45000
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      connection-timeout: 10000
      maximum-pool-size: 15
      minimum-idle: 5
      idle-timeout: 4500
      max-lifetime: 300000
      connection-test-query: SELECT 1
      validation-timeout: 3000
      leak-detection-threshold: 10000
      initialization-fail-timeout: 30000
      keepalive-time: 3000
      max-lifetime: 280000
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
  cache:
    caffeine:
      spec: initialCapacity=100,maximumSize=1000,expireAfterWrite=10m

server:
  port: ${PORT:8080}

logging:
  level:
    com.andesairlines: INFO
    org.springframework.cache: INFO
    org.springframework.retry: INFO
    org.springframework.web: INFO
    root: INFO