spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/checkin?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&socketTimeout=30000&connectTimeout=10000&tcpKeepAlive=true}
    username: ${DB_USERNAME:}
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000  # 10 minutes
      max-lifetime: 1800000  # 30 minutes
      minimum-idle: 5
      maximum-pool-size: 10
      connection-test-query: SELECT 1
      validation-timeout: 5000
      keepalive-time: 30000  # 30 seconds
      leak-detection-threshold: 60000  # 1 minute
      pool-name: HikariCP
      initialization-fail-timeout: 1
      connection-init-sql: SELECT 1
      auto-commit: false
      data-source-properties:
        socketTimeout: 30000
        connectTimeout: 10000
        useSSL: false
        allowPublicKeyRetrieval: true
        tcpKeepAlive: true
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        useCursorFetch: true
        maintainTimeStats: false
        useLocalTransactionState: true
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        connection.provider_disables_autocommit: true
        jdbc:
          time_zone: UTC
          batch_size: 20
        connection:
          provider_disables_autocommit: true
    open-in-view: false
  cache:
    caffeine:
      spec: initialCapacity=100,maximumSize=1000,expireAfterWrite=10m
  # Add this for Swagger
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

# Swagger configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    doc-expansion: none
  show-actuator: true

server:
  port: ${PORT:8080}
  servlet:
    context-path: /api

logging:
  level:
    com.andesairlines: INFO
    org.springframework.cache: INFO
    org.springframework.retry: INFO
    org.springframework.web: INFO
    org.springdoc: INFO
    root: INFO