spring:
  datasource:
    url: ${DB_URL}?useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-test-query: SELECT 1
      validation-timeout: 5000
      leak-detection-threshold: 60000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  cache:
    caffeine:
      spec: initialCapacity=50,maximumSize=200,expireAfterWrite=2m
logging:
  level:
    com.andesairlines: DEBUG
    org.springframework.cache: DEBUG
    org.springframework.retry: DEBUG
    org.hibernate.SQL: DEBUG